### ISSUE TITLE
borderRadius on image doesn't get animated (iOS only)

### ISSUE THREAD

**Issue by vitosorriso** [IjzerenHein/react-native-shared-element#26]
Hello everyone. I'm using `react-navigation-shared-elements` to achieve a transition similar to the app-of-the-day Apple's transition: everything works, except for the borderRadius on the image! It doesn't get animated, borderRadius is applied only at the end of transition; on android everything works fine!

    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-shared-element": "^0.5.6",
    "react-navigation": "^4.1.0",
    "react-navigation-shared-element": "^2.2.0",
    "react-navigation-stack": "^2.1.0",
    "react-navigation-tabs": "^2.7.0"

Code is very simple. This is the code from the list:

```js
// into render
        <SharedElement {...{ id }}>
          <Image resizeMode="cover" source={picture} style={styles.image} />
        </SharedElement>
// image style
  image: {
    width: screenWidth - 32,
    height: 210,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
```

This is the code into detail:

```js
// into render
        <SharedElement {...{ id }}>
          <Image resizeMode="cover" style={styles.image} source={picture} />
        </SharedElement>

// image style
  image: {
    width: screenWidth,
    height: screenWidth,
  },
```

That's it. I apply the borderRadius with a style on the image. Is this the good way to achieve this behavior?

Bug is the same as reported in the issue #14 (borderRadius only, I just quote the gif provided by @Hirbod). I also read that you already fixed it, because the default component to handle images on iOS was changed not so long time ago, but it is still there.

![RPReplay_Final1577464044](https://user-images.githubusercontent.com/504909/71526564-cff15200-28d7-11ea-9516-e8ff44f86610.gif)

_Originally posted by @Hirbod in https://github.com/IjzerenHein/react-native-shared-element/issues/14#issuecomment-569313330_

Thanks in advance for your time and this wonderful repository!

**Comment by IjzerenHein** [comment]
Yep you're right that is not fully supported yet. In previous versions of RN you could not set the border-radius for individual corners, but now you can. This is not yet fully supported on iOS.
Thanks for reporting, will take a look.

**Comment by IjzerenHein** [comment]
I've implemented multi corner-radii on iOS and released a test version to NPM. Could you test it whether it works for you?

```
yarn add react-native-shared-element@0.7.0-alpha0
```

**Comment by vitosorriso** [comment]
@IjzerenHein sorry for the delay, anyway I just tried this alpha version in combination of `react-navigation-shared-element ^2.2.0`, works like a charm! And nothing is broken on android! Thank you so much.

**Comment by IjzerenHein** [comment]
Awesome, great to hear! It should be fully compatible. Thanks for testing!

**Comment by vitosorriso** [comment]
Thank you for you effort and very fast resolving! I will keep the version locked to `react-native-shared-element@0.7.0-alpha0` in the package.json, please let us know when this fix is available on the stable branch!

**Comment by Hirbod** [comment]
And Expo users like me have to wait another 3 months 💔
I need to eject quickly :D

**Comment by mrousavy** [comment]
@IjzerenHein on android the border radius property still doesn't work, same bug as shown in @vitosorriso 's GIF. 
Any idea why? (I'm on v5 using `react-navigation-shared-element@next` and `react-native-shared-element@next`)

**Comment by IjzerenHein** [comment]
I've released a new version with the border-radii support per corner on iOS:
https://github.com/IjzerenHein/react-native-shared-element/releases/tag/v0.7.0

**Comment by Kinark** [comment]
It seems like when there's different border-radius on an element, it's shadow disappears on transition on iOS D:

**Comment by evanjmg** [comment]
This is still an issue

**Comment by MorganTrudeau** [comment]
I see this issue on android only...
